### ISSUE TITLE
Logo Design For electrochemistry

### ISSUE THREAD

**Issue by zularizal** [nealde/electrochemistry#1]
Hi @nealde , I'm a graphic designer. After I review your project, I am interested in designing a logo for your project. I want to create a logo that is relevant to your project. What do you think?

Best regards,
Zularizal

**Comment by nealde** [comment]
Wow, yeah, that would be awesome! Let me know if there's anything I can do to help!

**Comment by nealde** [comment]
sorry for the delay, I thought I responded - that second one is super cool!!

**Comment by zularizal** [comment]
Hi @nealde , I already uploaded the logo to drive

https://drive.google.com/open?id=1eN9XwAhoW9cA4RK-NZQNXlDvfNrm1In5

and also I have sent a pull request for you, check #2
